#!/bin/sh

terminal=footclient

$terminal -T htop htop &

swaymsg layout splitv && $terminal -T 'journalctl -f' journalctl -f &

#swaymsg layout splitv && $terminal -T 'tailf $WMLOG' zsh -i -c "tailf $WMLOG" &
