#!/bin/bash
#systemctl stop asd
systemctl stop systemd-timesyncd
systemctl stop rescached
systemctl stop dnscrypt-proxy.socket
systemctl stop iptables
killall dhcpcd
#killall wpa_supplicant
ip link set dev wls1 down
macchanger -A wls1
ip link set dev wls1 up
#wpa_supplicant -Dnl80211,wext -i wls1 -c <(wpa_passphrase "PLDTHOMEFIBR_BERGADO" "caseypatrice") &
iw dev wls1 connect -w "$1"
sleep 3s && dhcpcd wls1
sleep 5s && systemctl start dnscrypt-proxy.socket
systemctl start rescached
sleep 3s && systemctl start iptables
GW=$(ip route | awk '/default/ { print $3 }')
arptables -A INPUT ! -s $GW -j DROP; arptables -A OUTPUT ! -d $GW -j DROP
systemctl start systemd-timesyncd
#systemctl start asd
systemctl --failed
systemd-analyze
