#!/bin/sh
systemctl stop iptables
systemctl stop rescached
systemctl stop dnscrypt-proxy.socket
systemctl stop systemd-timesyncd
killall dhcpcd
ip link set dev wls1 down
macchanger -A wls1
ip link set dev wls1 up
iw dev wls1 connect -w "$1" && dhcpcd wls1 
systemctl start systemd-timesyncd 
systemctl start dnscrypt-proxy.socket && systemctl start rescached
systemctl start iptables


