icons = "awesome"

[theme]
name = "plain"
[theme.overrides]
# idle_bg = "#020202"
idle_bg = "#303030"
# idle_fg = "#b5b3aa"
idle_fg = "#d0d0d0"
# info_bg = "#020202"
info_bg = "#303030"
# info_fg = "#b5b3aa"
info_fg = "#d0d0d0"
# good_bg = "#020202"
good_bg = "#303030"
good_fg = "#2ca1a1"
warning_fg = "#e68900"
# warning_bg = "#020202"
warning_bg = "#303030"
# critical_bg = "#020202"
critical_bg = "#303030"
critical_fg = "#dd005f"
separator = ""
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"

[[block]]
block = "focused_window"
max_width = 30

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}C"
chip = "*-isa-*"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 15
warning = 10.0
alert = 5.0
alert_absolute = true

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
unit = "MB"
interval = 15
warning = 4000.0
alert = 1000.0
alert_absolute = true

[[block]]
block = "custom"
command = '/home/d0np0br3/.config/scripts/ssdtemp.sh' 
json = true

[[block]]
block = "net"
device = "wlan0"
format = "{speed_down;K*b} {speed_up;K*b}"
interval = 3
# use_bits = false

# [[block]]
# block = "music"
# player = "cmus"

[[block]]
block = "sound"
# driver = "alsa"

[[block]]
block = "backlight"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d/%Y %R"

