icons = "awesome"

[theme]
name = "plain"
[theme.overrides]
idle_bg = "#28292e"
idle_fg = "#93a1a1"
info_bg = "#28292e"
info_fg = "#93a1a1"
good_bg = "#28292e"
good_fg = "#2ca1a1"
warning_fg = "#e68900"
warning_bg = "#28292e"
critical_bg = "#28292e"
critical_fg = "#dd005f"
separator = ""
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"

[[block]]
block = "focused_window"
max_width = 25

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}°C"
chip = "*-isa-*"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mum} MB"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 10.0
alert = 5.0
alert_absolute = true

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "MB"
interval = 20
warning = 4000.0
alert = 1000.0
alert_absolute = true

[[block]]
block = "custom"
command = '/home/d0np0br3/.config/scripts/ssdtemp.sh' 
json = true

[[block]]
block = "net"
device = "wlan0"
format = "{speed_down} {speed_up}"
interval = 3
use_bits = false

[[block]]
block = "sound"
driver = "alsa"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d/%Y %R"

